

export const projectsConstants = [
  {
    name: "CloudSmiles",
    images: [
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738159765/cloudsmiles/prdl0baifxpiidvtm53e.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738159765/cloudsmiles/axgxymbhm87mwn2m6ysg.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738159766/cloudsmiles/kduq5zxdn29caczmrjgg.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738159765/cloudsmiles/cq1prekhqieyr2hmiqrt.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738159765/cloudsmiles/s2jnjsskuvdllocxtihp.webp",
    ],
    link: "https://www.vsdentalph.com",
    technologies: ["React", "MongoDB", "ExpressJS", "Cohere", "Cloudinary", "Redis", "TypeScript", "TailwindCSS"],
    tags: ["Management System", "Chatbot", "Appointments"],
    features: [
      "Real-time tracking and data visualization for clinic performance, patient flow, and appointment trends.",
      "System for tracking patient information such as medical history, treatment records, and appointments",
      "Allows patients to pay online for services, offering a more convenient and secure payment method.",
      "Tool for dentists to schedule and adjust treatment plans to ensure timely and accurate care.",
      "AI-powered chatbot that answers patient inquiries and assists with appointment bookings.",
      "An intuitive tool for scheduling appointments online, reducing the need for physical visits.",
      "Manages dental supplies and equipment, with alerts for low stock and timely reordering.",
      "Helps organize staff schedules, manage availability, and minimize conflicts.",
    ],    
    description: "A web-based system that allows patients to book an appointment, view their dental records, and chat with a chatbot assistant for dental questions.",
    isFeatured: true,
    isDeployed: true,
    createdAt: "November 26th 2024",
  },
  {
    name: "SkillSwap",
    images: [
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738151870/skillswap/nkb8u06fupesktnaf5hi.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738151870/skillswap/ezvabbdmmrpaybc16aiv.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738151870/skillswap/nmuiuaun7xmtezkvfapq.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738151870/skillswap/wpc8plxyrld7sehrrndz.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738151870/skillswap/iqqfnrcplzli5putnveo.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738151871/skillswap/roa6kfqfy8nvwnksgqhl.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738151871/skillswap/jpjct277ma0wrxxwwljr.webp",
    ],
    link: "https://skillswap-nu.vercel.app/",
    technologies: ["React", "NodeJS", "MongoDB", "JavaScript","Vite", "TailwindCSS", "Render", "Google Maps", "Socket"],
    tags: ["Social Media", "Messaging", "Generative Text"],
    features: [
      "Profile management system for users to maintain their skill and experience details.",
      "Skill trading platform for users to exchange skills with others.",
      "Audit trail for tracking actions and activities on the platform.",
      "Skill posting functionality for users to share their expertise.",
      "Realtime messaging system for user communication.",
    ],
    description: "A social media platform that allows users to swap their skills with other users. Users can post their skills and message other users for skill exchange.",
    isFeatured: true,
    isDeployed: true,
    createdAt: "September 16th 2023"
  },
  {
    name: "DocuTrace",
    images: [
      "https://res.cloudinary.com/dueebthen/image/upload/v1738057014/works/ovwzw7elxx20o3xvyvha.png",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738146549/docutrace/zcclvbxqe4lpnrweepqc.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738146549/docutrace/vsywr0mav5o1e5sik7oi.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738146549/docutrace/amqorrhkfog6q6lrmqjy.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738146550/docutrace/nnyiua0rrc3bfrz9jtel.webp",
    ],
    link: "https://www.docutrace.website",
    year: "2024",
    technologies: ["React", "NodeJS", "TypeScript", "MongoDB","Vite", "Redis", "Vercel"],
    tags: ["Progress Tracker", "Activity Logger"],
    features: [
      "Log activities related to document handling for audit and transparency.",
      "Automated document ticket generation for requests and updates.",
      "Receive notifications for document updates and changes.",
      "Generate detailed reports for document tracking.",
      "Track progress of document processing.",
    ],
    description: "A cloud-based system that allows employees to track their documents, request for documents, and receive notifications for document updates.",
    isFeatured: false,
    isDeployed: true,
    createdAt: "December 3rd 2024"
  },
  {
    name: "Pampanga Tourista",
    images: [
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738145129/pampangatourista/ev0jqsnvpuhjq9tmga8m.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738145132/pampangatourista/zlgfyrvpanhkzg0trjxu.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738145130/pampangatourista/ye8cjfa9o7j1kgaoeuhx.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738145130/pampangatourista/jwrgqoqxldcsn4wcxkyc.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738145130/pampangatourista/omqdv1x5d4uxooa1rbtz.webp",
    ],
    link: "https://www.pampangatourista.com",
    technologies: ["React", "NodeJS", "MongoDB", "TypeScript","Vite", "TailwindCSS", "Render", "Google Maps"],
    tags: ["Booking", "Ratings"],
    features: [
      "Autocompute fares and distances for convenient travel planning.",
      "Create and manage a personal itinerary for your tour.",
      "Realtime messaging for tourists and tour guides.",
      "Book tour guides for personalized experiences.",
      "Autocomplete map search for easy navigation.",
      "Add tourist spots and services to favorites.",
    ],
    description: "A web-based system that allows tourists to view tourist spots in Pampanga, view reviews, and book a tour guide.",
    isFeatured: false,
    isDeployed: true,
    createdAt: "September 12th 2024",
  },
  {
    name: "CerTrack",
    images: [
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738144047/certrack/ley5bues8m3zwdozg8bm.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738143901/certrack/esoyu1rquwutzeje3kto.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738143900/certrack/hba6vd4orlt02esyua8s.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738143900/certrack/p3xot5pcjuhg1wpe7qgi.webp",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738143900/certrack/iipalhzke52itlfz5qjw.webp",
    ],
    link: "https://www.doh-service.online/login",
    technologies: ["React", "NodeJS", "MongoDB", "JavaScript","Vite", "TailwindCSS", "Render"],
    tags: ["Training Tracker", "Certificate Editor"],
    features: [
      "Trainee profile management for tracking individual achievements.",
      "Generate reports for training activities and certificate issuance.",
      "Audit trail for tracking actions and changes in the system.",
      "Certificate editor for creating and managing certificates.",
      "Training tracker to monitor progress and completions.",
    ],
    description: "A web-based system that allows users to track their certificates, request for certificates, and receive notifications for training updates.",
    isFeatured: false,
    isDeployed: true,
    createdAt: "September 1st 2024"
  },
  {
    name: "FarmSphere",
    images: [
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738140665/farmsphere/rmbksvf4nhkwg3bllzxk.png",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738140664/farmsphere/i4awqvzkoyovdnaofzk8.png",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738140665/farmsphere/kqppwxgnj6n24dqcmjvo.png",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738140665/farmsphere/xa5hsjljjtlqup53bgla.png",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738140665/farmsphere/mqfpqejl1xcdfho63l6a.png",
      "https://res.cloudinary.com/dy5j494og/image/upload/v1738140666/farmsphere/po13wdj9ilhe6i8mfooh.png",
    ],
    link: null,
    technologies: ["Blockchain","NodeJS","React",  "TypeScript","Vite", "TailwindCSS"],
    tags: [ "Crop Tracker", "Blockchain"],
    features: [
      "Interactive map displaying the number of crops harvested each month when a region is selected.",
      "Adding new crops report for updated tracking and analysis.",
      "Analytic dashboard for monitoring crop data and trends.",
      
    ],
    description: "A web-based system that allows users to track their certificates, request for certificates, and receive notifications for training updates.",
    isFeatured: false,
    isDeployed: false,
    createdAt: "October 9th 2024",
  },
]